insert into distributor ([name], phone#, email, [address]) values ('Skyba', '6609746269', 'smaxfield0@sitemeter.com', '67533 Hazelcrest Park');
insert into distributor ([name], phone#, email, [address]) values ('Ntags', '5049828711', 'kwilfinger1@nba.com', '1850 Laurel Court');
insert into distributor ([name], phone#, email, [address]) values ('Skipstorm', '9108775422', 'aderwin2@zimbio.com', '9 Glacier Hill Park');
insert into distributor ([name], phone#, email, [address]) values ('Mynte', '9875565735', 'kmuggeridge3@scribd.com', '6 New Castle Court');
insert into distributor ([name], phone#, email, [address]) values ('Yabox', '9649458064', 'astove4@dot.gov', '5703 Menomonie Center');
insert into distributor ([name], phone#, email, [address]) values ('Jayo', '5913899546', 'cgiddins5@blogger.com', '0673 8th Drive');
insert into distributor ([name], phone#, email, [address]) values ('Kare', '2288128384', 'afallen6@bandcamp.com', '23 Rowland Court');
insert into distributor ([name], phone#, email, [address]) values ('Voonte', '5298027024', 'rveitch7@hhs.gov', '369 Bonner Point');
insert into distributor ([name], phone#, email, [address]) values ('Divanoodle', '5054070480', 'vblincko8@quantcast.com', '358 Anniversary Center');
insert into distributor ([name], phone#, email, [address]) values ('Riffpath', '3604638252', 'vwhytock9@miitbeian.gov.cn', '8 Packers Junction');
insert into distributor ([name], phone#, email, [address]) values ('Browsecat', '2444924719', 'llelliotta@istockphoto.com', '42239 Bunting Junction');
insert into distributor ([name], phone#, email, [address]) values ('Fliptune', '8118999915', 'eleidenb@mozilla.com', '91949 Fallview Terrace');
insert into distributor ([name], phone#, email, [address]) values ('Skynoodle', '7185640274', 'schiommientic@tinyurl.com', '706 Hagan Pass');
insert into distributor ([name], phone#, email, [address]) values ('Realblab', '3696619692', 'sletterickd@youku.com', '020 Garrison Alley');
insert into distributor ([name], phone#, email, [address]) values ('Quimm', '9428278953', 'sghiroldie@biglobe.ne.jp', '6 Loeprich Crossing');
insert into distributor ([name], phone#, email, [address]) values ('Jaxnation', '8932021455', 'bolivaf@nsw.gov.au', '9 Butterfield Lane');
insert into distributor ([name], phone#, email, [address]) values ('Wordware', '4047388893', 'wverrillg@rambler.ru', '258 Arrowood Circle');
insert into distributor ([name], phone#, email, [address]) values ('Skyvu', '4366623679', 'oyanceyh@google.ru', '69 Oriole Circle');
insert into distributor ([name], phone#, email, [address]) values ('Avamm', '5704882272', 'slapworthi@tamu.edu', '78038 Golf Course Trail');
insert into distributor ([name], phone#, email, [address]) values ('Linkbridge', '4704684617', 'bheigoldj@cdc.gov', '7 Thierer Way');
