insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('air filter change', 74.8, 3.07, 2.32);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('battery replacement', 53.57, 4.08, 3.86);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('brake repair', 70.07, 0.68, 3.55);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('camshaft replacement', 81.82, 4.63, 3.99);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('catalytic converter replacement', 56.31, 1.89, 2.71);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('coolant recycle', 61.27, 4.1, 0.05);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('drive belt replacement', 87.07, 4.68, 3.21);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('engine oil change', 66.36, 1.72, 1.16);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('gearbox repair', 55.4, 2.19, 0.8);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('headlights replacement', 93.95, 0.41, 3.97);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('oil filter change', 94.12, 2.74, 2.98);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('piston replacement', 80.24, 3.38, 3.45);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('power steering replacement', 95.14, 4.73, 4.61);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('spark plugs replacement', 87.43, 0.33, 2.76);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('tail lights replacement', 81.99, 2.06, 2.2);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('turn lights replacement', 56.01, 4.85, 3.04);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('valve replacement', 54.12, 3.99, 2.72);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('wheel alignment', 79.82, 3.48, 3.5);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('wiper replacement', 76.8, 3.46, 1.26);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('tire replacement', 58.89, 4.77, 1.96);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('wheel pump', 84.38, 1.97, 1.85);
insert into micro_service ([name], charge_per_hour, min_hour, max_hour) values ('tire rotation', 81.39, 4.45, 1.28);
