insert into model (brand#, [name], [year]) values (1, 'Mirage', 1998);
insert into model (brand#, [name], [year]) values (5, '300', 2007);
insert into model (brand#, [name], [year]) values (7, 'Century', 1993);
insert into model (brand#, [name], [year]) values (1, '4Runner', 2006);
insert into model (brand#, [name], [year]) values (5, 'Trooper', 2000);
insert into model (brand#, [name], [year]) values (12, 'Highlander', 2001);
insert into model (brand#, [name], [year]) values (6, '9000', 1987);
insert into model (brand#, [name], [year]) values (7, '240SX', 1995);
insert into model (brand#, [name], [year]) values (4, 'Land Cruiser', 2008);
insert into model (brand#, [name], [year]) values (14, 'Navajo', 1994);
insert into model (brand#, [name], [year]) values (14, '3 Series', 1994);
insert into model (brand#, [name], [year]) values (11, 'Grand Cherokee', 2007);
insert into model (brand#, [name], [year]) values (14, 'Flex', 2013);
insert into model (brand#, [name], [year]) values (2, 'Magnum', 2005);
insert into model (brand#, [name], [year]) values (3, 'LeBaron', 1994);
insert into model (brand#, [name], [year]) values (9, '9000', 1999);
insert into model (brand#, [name], [year]) values (4, 'LeMans', 1991);
insert into model (brand#, [name], [year]) values (14, 'Trans Sport', 1990);
insert into model (brand#, [name], [year]) values (7, 'Aventador', 2012);
insert into model (brand#, [name], [year]) values (13, 'MX-6', 1994);
insert into model (brand#, [name], [year]) values (7, 'Equinox', 2009);
insert into model (brand#, [name], [year]) values (10, 'Maxima', 2003);
insert into model (brand#, [name], [year]) values (1, 'Ranger', 1986);
insert into model (brand#, [name], [year]) values (3, 'Expo', 1995);
insert into model (brand#, [name], [year]) values (14, 'Discovery', 1998);
insert into model (brand#, [name], [year]) values (6, 'Insight', 2006);
insert into model (brand#, [name], [year]) values (14, 'Cherokee', 1992);
insert into model (brand#, [name], [year]) values (1, 'Escalade ESV', 2008);
insert into model (brand#, [name], [year]) values (2, 'Concorde', 1995);
insert into model (brand#, [name], [year]) values (0, 'S-Class', 2006);
insert into model (brand#, [name], [year]) values (3, '626', 2000);
insert into model (brand#, [name], [year]) values (11, 'Rally Wagon 3500', 1992);
insert into model (brand#, [name], [year]) values (3, 'Vanagon', 1984);
insert into model (brand#, [name], [year]) values (10, 'Milan', 2008);
insert into model (brand#, [name], [year]) values (4, 'Ram 1500', 2007);
insert into model (brand#, [name], [year]) values (3, 'Sorento', 2003);
insert into model (brand#, [name], [year]) values (5, '62', 2011);
insert into model (brand#, [name], [year]) values (7, 'Explorer', 2003);
insert into model (brand#, [name], [year]) values (2, 'Expo', 1992);
insert into model (brand#, [name], [year]) values (12, 'Galant', 2008);
insert into model (brand#, [name], [year]) values (9, 'Tercel', 1998);
insert into model (brand#, [name], [year]) values (12, 'Esperante', 2008);
insert into model (brand#, [name], [year]) values (3, 'Camry', 2004);
insert into model (brand#, [name], [year]) values (6, 'Mustang', 2010);
insert into model (brand#, [name], [year]) values (14, 'Grand Cherokee', 2010);
insert into model (brand#, [name], [year]) values (13, 'Solara', 2007);
insert into model (brand#, [name], [year]) values (11, 'Avanti', 1964);
insert into model (brand#, [name], [year]) values (0, 'Prizm', 1994);
insert into model (brand#, [name], [year]) values (8, 'SC', 2004);
insert into model (brand#, [name], [year]) values (14, 'Expedition', 2000);
insert into model (brand#, [name], [year]) values (6, '6000', 1988);
insert into model (brand#, [name], [year]) values (14, 'Explorer', 2004);
insert into model (brand#, [name], [year]) values (3, 'Focus', 2010);
insert into model (brand#, [name], [year]) values (4, 'Ram Van B250', 1992);
insert into model (brand#, [name], [year]) values (7, 'G35', 2003);
insert into model (brand#, [name], [year]) values (7, 'RX-7', 1986);
insert into model (brand#, [name], [year]) values (0, 'Fox', 1987);
insert into model (brand#, [name], [year]) values (13, 'PT Cruiser', 2010);
insert into model (brand#, [name], [year]) values (9, 'Civic', 1996);
insert into model (brand#, [name], [year]) values (9, 'Ranger', 1990);
insert into model (brand#, [name], [year]) values (4, 'CTS-V', 2011);
insert into model (brand#, [name], [year]) values (13, 'Q7', 2010);
insert into model (brand#, [name], [year]) values (7, 'F150', 1995);
insert into model (brand#, [name], [year]) values (9, 'Prius', 2006);
insert into model (brand#, [name], [year]) values (1, 'Express 3500', 2012);
insert into model (brand#, [name], [year]) values (4, 'Esperante', 2007);
insert into model (brand#, [name], [year]) values (14, 'GL-Class', 2009);
insert into model (brand#, [name], [year]) values (11, 'Seville', 2001);
insert into model (brand#, [name], [year]) values (12, 'Avenger', 2011);
insert into model (brand#, [name], [year]) values (6, 'CL-Class', 2000);
insert into model (brand#, [name], [year]) values (13, 'Insight', 2005);
insert into model (brand#, [name], [year]) values (8, 'Coupe GT', 1987);
insert into model (brand#, [name], [year]) values (11, 'HHR', 2009);
insert into model (brand#, [name], [year]) values (9, 'Century', 1999);
insert into model (brand#, [name], [year]) values (8, 'F-Series', 2009);
insert into model (brand#, [name], [year]) values (7, '9-3', 2008);
insert into model (brand#, [name], [year]) values (8, 'Sebring', 2004);
insert into model (brand#, [name], [year]) values (6, 'Ram Van 2500', 1999);
insert into model (brand#, [name], [year]) values (4, 'STS-V', 2009);
insert into model (brand#, [name], [year]) values (3, 'Corvette', 2005);
insert into model (brand#, [name], [year]) values (1, 'Venture', 2001);
insert into model (brand#, [name], [year]) values (8, 'IS', 2009);
insert into model (brand#, [name], [year]) values (11, '960', 1993);
insert into model (brand#, [name], [year]) values (0, 'Sportvan G10', 1993);
insert into model (brand#, [name], [year]) values (6, 'M3', 2012);
insert into model (brand#, [name], [year]) values (0, 'Ghost', 2012);
insert into model (brand#, [name], [year]) values (10, 'Escalade EXT', 2007);
insert into model (brand#, [name], [year]) values (12, 'Frontier', 2012);
insert into model (brand#, [name], [year]) values (6, 'IS', 2006);
insert into model (brand#, [name], [year]) values (2, 'Dakota', 2009);
insert into model (brand#, [name], [year]) values (1, '7 Series', 2004);
insert into model (brand#, [name], [year]) values (8, 'Protege', 1992);
insert into model (brand#, [name], [year]) values (5, '3 Series', 2006);
insert into model (brand#, [name], [year]) values (0, 'CX-7', 2008);
insert into model (brand#, [name], [year]) values (10, 'Escalade EXT', 2008);
insert into model (brand#, [name], [year]) values (7, 'S5', 2008);
insert into model (brand#, [name], [year]) values (9, 'M-Class', 2007);
insert into model (brand#, [name], [year]) values (13, 'Gallardo', 2006);
insert into model (brand#, [name], [year]) values (3, 'Grand Cherokee', 2003);
insert into model (brand#, [name], [year]) values (3, 'Grand Cherokee', 2009);